# -*- coding: utf-8 -*-
"""Introdução a Machine Learning e Classificação -1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13KnDAZbLpGPbsBJuSH4XhgWUCeOgL6q7
"""

# features
# pelo longo?
# perna curta?
# faz auau?

porco1 = [0, 1, 0]
porco2 = [0, 1, 1]
porco3 = [1, 1, 0]

cachorro1 = [0, 1, 1]
cachorro2 = [1, 0, 1]
cachorro3 = [1, 1, 1]

treino_x = [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
treino_y = [1,1,1,0,0,0]

from sklearn.svm import LinearSVC
model = LinearSVC()
model.fit(treino_x, treino_y)

animal_misterioso = [1,1,1]
model.predict([animal_misterioso])

misterio1 = [1,1,1]
misterio2 = [1,1,0]
misterio3 = [0,1,1]

testes_x = [misterio1, misterio2, misterio3]
testes_y = [0,1,1]

previsoes = model.predict(testes_x)

corretos = (previsoes == testes_y).sum()
total = len(testes_x)
taxa_de_acerto = corretos/total
print("Taxa de Acerto: %.2f" % (taxa_de_acerto * 100))

from sklearn.metrics import accuracy_score
taxa_de_acerto = accuracy_score(testes_y, previsoes)
print("Taxa de Acerto: %.2f" % (taxa_de_acerto * 100))